version: "2.1"

# USAGE (cd to project root): docker-compose -f ./setup/<docker-compose>.yml up 
services:
  nodejs:
    build:
      context: ../
      dockerfile: ./configuration/container/server.dockerfile    
    image: myuserindocker/animalsounds-webapp:latest
    command: node /app/source/serverSide/nodeServer/server.js
    ports:
      - "80:80"
