version: "3.7"

services:
  nodejs:
    image: myuserindocker/animalsounds-webapp:latest
    environment:
      DEPLOYMENT: production
    ports: 
      - 80:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
