version: '3.3'

networks: 
  internal:
    external: false
  proxy:
    external: true

services:

  nodejs:
    image: myuserindocker/animalsounds-webapp:latest
    environment:
      DEPLOYMENT: production
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - internal
      - proxy